insert into user(id,password) values(1,"1");
insert into user(id,password) values(2,"2");
insert into user(id,password) values(3,"3");
insert into user(id,password) values(4,"4");
insert into user(id,password) values(5,"5");
insert into user(id,password) values(6,"6");
insert into user(id,password) values(7,"7");
insert into user(id,password) values(8,"8");
insert into user(id,password) values(9,"9");
