DROP DATABASE IF EXISTS BANK;
CREATE DATABASE BANK DEFAULT CHARSET UTF8;
USE BANK;
CREATE TABLE USER
(
    ID           INT UNSIGNED PRIMARY KEY,
    PASSWORD     VARCHAR(20) NOT NULL,
    NAME         VARCHAR(20),
    PHONE_NUMBER VARCHAR(20),
    ADDRESS      VARCHAR(100)
) ENGINE = INNODB;
CREATE TABLE BILL
(
    SENDER INT UNSIGNED,
    PAYEE  INT UNSIGNED,
    VALUE  DOUBLE,
    TYPE   VARCHAR(20),
    FOREIGN KEY (SENDER) REFERENCES USER (ID),
    FOREIGN KEY (PAYEE) REFERENCES USER (ID)
);
CREATE TABLE BANKCARD
(
    BANKCARDNUMBER    INT UNSIGNED PRIMARY KEY,
    PASSWORD          VARCHAR(25) NOT NULL,
    REMAINING_BALANCE DOUBLE DEFAULT 0.00,
    BANK_NAME         VARCHAR(20)
) ENGINE = INNODB;
CREATE TABLE USER_BANKCARD
(
    USERID         INT UNSIGNED,
    BANKCARDNUMBER INT UNSIGNED,
    PRIMARY KEY (USERID, BANKCARDNUMBER),
    FOREIGN KEY (USERID) REFERENCES USER (ID)
) ENGINE = INNODB;
CREATE TABLE LOAN
(
    ID           INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    INTERESTRATE DOUBLE      NOT NULL,
    NAME         VARCHAR(20) NOT NULL,
    DETIAL       VARCHAR(100)
) ENGINE = INNODB;
insert into loan(INTERESTRATE, name, detial)
values (1.0032, "低利息贷款", "每年只还0.0032%");
insert into loan(INTERESTRATE, name, detial)
values (1.18, "高利息贷款", "每年只还0.18%");
insert into loan(INTERESTRATE, name, detial)
values (1.045, "中利息贷款", "每年只还0.0045%");
insert into loan(INTERESTRATE, name, detial)
values (1.00, "无利息贷款", "须在三个月内还清");
insert into loan(INTERESTRATE, name, detial)
values (1.00, "抵押利息贷款", "需抵押你家房子");