GET http://localhost:8080/user/login?username=asdf&password=asdf
Accept: application/json

###
http://localhost:8080/user/login?username=&password=
Accept: application/json

###
http://localhost:8080/user/login?username=453&password=344
Accept: application/json

###
GET http://localhost:8080/in
Accept: application/json

###
###
GET localhost:8080/login

<> 2021-08-06T141349.200.txt